name: flutter_weather_demo
publish_to: none
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  command_it: ^9.0.2
  watch_it:
    path: ../
  listen_it: ^5.3.3

flutter:
  uses-material-design: true
