name: watch_it
description: The simple state management powered by get_it. It allows to observe changes of objects inside the get_it service locator and rebuild the UI accordingly.
version: 2.1.1
homepage: https://github.com/flutter-it/watch_it
funding:
  - https://github.com/sponsors/escamoteur/

screenshots:
  - description: 'watch_it logo'
    path: watch_it.png

environment:
  sdk: '>=2.19.6 <4.0.0'
  flutter: ">=3.0.0"

topics:
  - state-management
  - dependency-injection
  - architecture
  - get-it

dependencies:
  get_it: ^9.0.5
  listen_it: ^5.3.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
